---
Title: Stickers
hero_image: images/stickers.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Stickers!
description: Maak grappige robotstickers om je webpagina's te versieren.
original_url: https://codeclubprojects.org/en-GB/webdev/stickers
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
- title: Inleiding
  completion: engaged
- title: Kleurrijke code sticker
- title: HTML & CSS-sticker
- title: 'Uitdaging: maak je eigen sticker met verloop'
- title: 'Leuke robot sticker '
  completion: internal
- title: 'Uitdaging: meer stickers maken'
