---
Title: Stickers
hero_image: images / stickers.png
theme: oranje
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Stickers!
description: Maak leuke robotstickers om je webpagina's te versieren.
original_url: https://codeclubprojects.org/en-GB/webdev/stickers
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Invoering
  - 
    title: Kleurrijke coderingssticker
  - 
    title: HTML & CSS-sticker
  - 
    title: 'Uitdaging: maak je eigen verloopsticker'
  - 
    title: Fancy robot sticker 
  - 
    title: 'Uitdaging: meer stickers maken'
