---
Title: Stickers
hero_image: images/stickers.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Stickers!
description: Create fun robot stickers to decorate your web pages.
original_url: https://codeclubprojects.org/en-GB/webdev/stickers
interests: 'art and design'
technologies: html/css
site_areas: codeclub, webdev
steps:
  - 
    title: Introduction
  - 
    title: Colourful coding sticker
  - 
    title: HTML & CSS sticker
  - 
    title: 'Challenge: Create your own gradient sticker'
  - 
    title: Fancy robot sticker 
  - 
    title: 'Challenge: Make more stickers'

