---
Title: Stickers
hero_image: images/stickers.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Stickers!
description: Create fun robot stickers to decorate your web pages.
original_url: https://codeclubprojects.org/en-GB/webdev/stickers
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introduction
  - 
    title: Colourful coding sticker
  - 
    title: HTML & CSS sticker
    completion:
      - engaged
  - 
    title: 'Challenge: Create your own gradient sticker'
  - 
    title: 'Fancy robot sticker '
    completion:
      - internal
  - 
    title: 'Challenge: Make more stickers'
