---
Title: '¡Pegatinas!'
hero_image: images/stickers.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: '¡Pegatinas!'
description: Crea pegatinas divertidas de robots para decorar tus páginas web.
original_url: https://codeclubprojects.org/en-GB/webdev/stickers
interests: arte
technologies: html-css-javascript
site_areas: proyectos
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introducción
  - 
    title: Crear una pegatina con degradado lineal
  - 
    title: Crea una pegatina con degradado radial
  - 
    title: 'Crea una pegatina con degradado que contenga una imagen'
  - 
    title: 'Degradados horizontales'
  - 
    title: 'Degradados diagonales'
