---
Title: Aufkleber
hero_image: images/stickers.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Aufkleber!
description: Fertige ein paar tolle Roboter-Aufkleber an, um deine Webseiten damit zu dekorieren.
original_url: https://codeclubprojects.org/en-GB/webdev/stickers
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Einführung
  - 
    title: Farbig kodierte Aufkleber
  - 
    title: HTML und CSS Aufkleber
  - 
    title: 'Aufgabe: Erstelle deinen eigenen Gradienten-Aufkleber'
  - 
    title: 'Ausgefallener Roboter-Aufkleber'
  - 
    title: 'Aufgabe: Noch mehr Aufkleber erstellen'
