---
Title: Stickere
hero_image: images/stickers.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Stickere!
description: Crerează stickere-robot amuzante pentru a-ți decora paginile web.
original_url: https://codeclubprojects.org/en-GB/webdev/stickers
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introducere
  - 
    title: Sticker colorat
  - 
    title: Sticker HTML & CSS
  - 
    title: 'Provocare: Creează-ți propriul sticker cu gradient'
  - 
    title: 'Sticker mișto cu robot '
  - 
    title: 'Provocare: Realizează mai multe stickere'
