---
Title: Adesivos
hero_image: images/stickers.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Adesivos!
description: Crie adesivos divertidos de robôs para decorar suas páginas da web.
original_url: https://codeclubprojects.org/en-GB/webdev/stickers
interests: arte
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 01/01/2017
steps:
- title: Introdução
  completion: engaged
- title: Adesivo colorido sobre Programação
- title: Adesivo de HTML & CSS
- title: 'Desafio: criar seu próprio adesivo com gradiente'
- title: 'Adesivo de robô enfeitado '
  completion: internal
- title: 'Desafio: faça mais adesivos'
