---
Title: Stickers
hero_image: images/stickers.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Stickers!
description: Crea divertidos stickers de robots para decorar tus páginas web.
original_url: https://codeclubprojects.org/en-GB/webdev/stickers
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
- title: Introducción
- title: Sticker colorido de programación
- title: Sticker HTML y CSS
  completion:
  - engaged
- title: 'Desafío: crea tu propio sticker degradado'
- title: Sticker elegante de un robot
  completion:
  - internal
- title: 'Desafío: crea más stickers'
