---
Title: Naljepnice
hero_image: images/stickers.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Naljepnice!
description: Napravi zabavne naljepnice sa robotima za ukrašavanje svojih veb-stranica.
original_url: https://codeclubprojects.org/en-GB/webdev/stickers
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
- title: Uvod
- title: Naljepnica o programiranju u više boja
- title: HTML & CSS naljepnica
  completion:
  - engaged
- title: 'Izazov: Kreiraj svoju naljepnicu sa gradijentom'
- title: 'Ukrašena naljepnica sa robotom '
  completion:
  - internal
- title: 'Izazov: Napravi više naljepnica'
