---
Title: Autocollants
hero_image: images/stickers.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Autocollants!
description: Créez des autocollants de robot amusants pour décorer tes pages Web.
original_url: https://codeclubprojects.org/en-GB/webdev/stickers
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
- title: Introduction
  completion: engaged
- title: Autocollant de codage coloré
- title: Autocollant HTML & CSS
- title: 'Défi: Crée ton propre autocollant dégradé'
- title: Autocollant robot fantaisiste
  completion: internal
- title: 'Défi: Faire plus d''autocollants'
